# Generated by Django 2.2 on 2020-10-17 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_category', related_query_name='items', to='adminPanel.Category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='locations',
            field=models.ManyToManyField(related_name='item_location', related_query_name='items', to='adminPanel.Location'),
        ),
        migrations.AlterField(
            model_name='item',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_subcategory', related_query_name='items', to='adminPanel.SubCategory'),
        ),
    ]
