# Generated by Django 3.1 on 2020-10-25 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='post_code',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
