# Generated by Django 3.1 on 2020-10-19 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0002_auto_20201017_2036'),
        ('adminPanel', '0003_locationhour'),
    ]

    operations = [
    ]
