# Generated by Django 2.2 on 2020-10-22 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0003_locationhour'),
        ('adminPanel', '0002_auto_20201017_2036'),
    ]

    operations = [
    ]
