# Generated by Django 2.2 on 2020-10-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0004_merge_20201019_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
