# Generated by Django 2.2 on 2020-10-23 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0004_merge_20201019_0958'),
        ('adminPanel', '0004_merge_20201022_0328'),
    ]

    operations = [
    ]
