# Generated by Django 3.1 on 2020-10-24 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0004_merge_20201019_0958'),
        ('adminPanel', '0004_merge_20201022_0328'),
        ('adminPanel', '0005_location_phone'),
    ]

    operations = [
    ]
