# Generated by Django 2.2 on 2020-10-25 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0005_location_phone'),
        ('adminPanel', '0005_merge_20201023_0124'),
    ]

    operations = [
    ]
